### ISSUE TITLE
Custom Tailwind Config

### ISSUE THREAD

**Issue by tobimori** [marcorieser/tailwind-merge-statamic#1]
Necessary for solving this issue: https://github.com/gehrisandro/tailwind-merge-php/issues/4

**Comment by marcorieser** [comment]
I guess there is nothing to do for me here. As soon as Sandro has a fix for that it's automatically available trough our dependencies. Or did I miss the point here?

**Comment by tobimori** [comment]
Tailwind Merge PHP/Laravel already has the option to supply a config and the solution to the issue is to supply a config. Your  plugin should therefore expose a config file where you can set the config that's used to initialize the tailwind merge object like here: https://github.com/gehrisandro/tailwind-merge-php/issues/4#issuecomment-1711875097

**Comment by marcorieser** [comment]
Does publishing the config file (as stated in the Laravel package docs) not work for you? Have not tested but since Statamic uses Laravel under the hood I guess it should work already.

**Comment by tobimori** [comment]
I see, I'll have to test this.

**Comment by marcorieser** [comment]
@tobimori did it work?
